### ISSUE TITLE
Excel template - add columns

### ISSUE THREAD

**Issue by toddhay-NOAA** [nwfsc-fram/research-catch-db#12]
Add the following columns to the excel template:

- [x] Add ComboBox for depth bins for yelloweye, canary, cowcode
- [x] add % released at depth column

**Comment by SaOgaz-NOAA** [comment]
Sent a copy of these changes to Kate and Kayleigh for approval.

**Comment by SaOgaz-NOAA** [comment]
We've got the final version of this locked down. Closing this ticket
