### ISSUE TITLE
add warnings to log in page

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/research-catch-db#49]
Login page is super sparse right now, doesn't give notification if log in doesn't work. Change password etc buttons aren't hooked up... leave those, implement them?

**Comment by SaOgaz-NOAA** [comment]
Hmm... this "works",  but it also appears that bnauth(?) gives a total misnomer of an error when the pw is wrong. Should look into that at some point.

**Comment by ghost** [comment]
Indeed, bn-auth gets whatever error msg from AUA and passes it along. We could "translate it" perhaps

**Comment by SaOgaz-NOAA** [comment]
Hmmm. Would you expect this... bad pw gave me a "Error: User not authorized for BOATNET_OBSERVER"

**Comment by ghost** [comment]
That's straight from AUA, yes. (Generally auth failures should be generic and not specify why they failed)

**Comment by SaOgaz-NOAA** [comment]
Okay. For now I'll just change it to some generalized error. Not sure if we want to also do this for obs-web  @sethgerou-noaa
